#Definition of specific targets (to use "Clean" and "mrproper")
.PHONY: clean, mrproper

#Desactivation of implicit rules (to write manually all rules)
.SUFFIXES:

#Compilator
#$@ : name of the target
#$^ : all dependancies of depencies list
#$< : first dependancy of depencies list
#-c : to not link (to generate a ".o" file)
CC=gcc #Compilator used (gcc, g++, etc.)
CFLAGS=-W -Wall #Compilation options
LDFLAGS= #No library to link
#Usually : 
#prefix=/usr/local/   		For added libraries
#INCLUDEDIR=${prefix}/include  	Directory of .h files
#LIBDIR=${prefix}/lib  		Directory of .a or .so files
#LDFLAGS= -I${INCLUDEDIR} -L${LIBDIR} -lnameofthelibrary
EXEC=Hello #Name of the executable

all: main.o hello.o
	$(CC) $^ -o $(EXEC) $(LDFLAGS)

#To generate all ".o" files based from ".c" files
%.o: %.c
	$(CC) -c $< -o $@ $(CFLAGS)

clean: 
	rm -rf *.bak #Delete all ".bak" files
	rm -rf *.o   #Delete all ".o" files
	rm -rf *~    #Delete all "~" files generated by gedit

mrproper: clean 
	rm -rf Hello #Delete all the project
